<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>answers calendar quest: <?php echo $this->layout_title ?></title>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<?
		$this->include_css_files();
		$this->include_js_files();
		?>
	</head>

	<body>
		<?= $this->print_view(); ?>
	</body>
</html>
