<div id="container">
 	
	<section id="calendar"></section>

	<section class="event-entry-box"  style="display:none;">
		<article>
			<h4>Create/Edit event for <span class="event-entry-title-date"></span></h4>
			<form id="add-event-form">
				<input type="text" name="title" placeholder="title">
				<input type="text" name="start" placeholder="event start">
				<input type="text" name="end" placeholder="event end">
				<input type="text" name="description" placeholder="description">
				<input type="hidden" name = "user_id" value="1">
				<input type="hidden" name = "id" value="">

				<a href="#" class="save">Save</a>
				<a href="#" class="cancel">Cancel</a>
			</form>
		</article>
	</section>

	<section class="event-details-box">
		<article>
			<h4 class="event-title"></h4>
			<p>
				<span class="event-start"></span>
				<span class="event-end"></span>
			</p>
			<p class="event-description"></p>
			<div class="arrow"></div>
		</article>
		<a href="#" class="edit">edit</a>
		<a href="#" class="delete">delete</a>
		<a href="#" class="cancel">cancel</a>
	</section>

	<div class="loading">
		
	</div>
</div>

<pre class="debug">
	<?php //print_r($this) ?>
</pre>